<?php

/**
 * @file
 * Primary module hooks for renify_dupr module.
 */

function renify_dupr_form_alter(&$form, &$form_state, &$form_id) {
  if ($form_id == 'renify_dupr_config') {}

  if ($form_id == 'node_players_edit_form') {
    $roles = \Drupal::currentUser()->getRoles();
    if (!in_array('administrator', $roles)) {
      $form['title']['widget'][0]['value']['#attributes']['disabled'] = 'disabled';
    }
  }
}

/**
 * Implements hook_cron().
 */
function renify_dupr_cron() {
  // \Drupal::service('renify_dupr.refresh_service')->refreshAllPlayers();
  // \Drupal::service('renify_dupr.match_service')->syncAll();
}
