<?php

/**
 * @file
 * Primary module hooks for renify_tournament module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\CloseModalDialogCommand;
use Drupal\Core\Ajax\RedirectCommand;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Url;

/**
 * Implements hook_preprocess_page().
 */
function renify_tournament_preprocess_page(&$vars) {
  $vars['#attached']['library'][] = 'renify_tournament/ajax-link';
}

/**
 * Implements hook_entity_extra_field_info().
 * Add upload csv on tournaments page.
 */
function renify_tournament_entity_extra_field_info() {
  $extra['node']['tournaments']['display']['pairing_csv_form'] = [
    'label' => t('Pairing CSV Generator Form'),
    'description' => t('Displays the CSV upload form for pairings.'),
    'weight' => 100,
    'visible' => TRUE,
  ];
  return $extra;
}

/**
 * Implements hook_node_view().
 */
function renify_tournament_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->bundle() === 'tournaments' && $display->getComponent('pairing_csv_form')) {
    // Check if the current user has the specific permission
    if (\Drupal::currentUser()->hasPermission('import tournament pairings')) {
      $build['pairing_csv_form'] = \Drupal::formBuilder()->getForm(
        'Drupal\renify_tournament\Form\PairingCsvUploadForm',
        $entity->id()
      );
    }
  }
}

/**
 * Implements hook_theme().
 */
function renify_tournament_theme($existing, $type, $theme, $path) {
  return [
    'group_stage' => [
      'variables' => [
        'tournament_id' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_entity_type_alter().
 */
function renify_tournament_entity_type_alter(array &$entity_types) {
  if (isset($entity_types['node'])) {
    // This forces the node entity to recognize 'offcanvas' as a valid form operation.
    $entity_types['node']->setFormClass('offcanvas', 'Drupal\node\NodeForm');
    $entity_types['node']->setFormClass('score', 'Drupal\node\NodeForm');
  }
}

/**
 * Implements hook_entity_update().
 */
function renify_tournament_entity_update(EntityInterface $entity) {
  if ($entity->getEntityTypeId() === 'node' && $entity->bundle() === 'match_tournament') {
    \Drupal::service('renify_tournament.score_generator')->save($entity);
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for node_form.
 */
function renify_tournament_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Check if we are in our specific form mode.
  $form_display = $form_state->getStorage()['form_display'] ?? NULL;

  if ($form_display && $form_display->getMode() === 'offcanvas') {
    // Add our custom AJAX callback to the submit button.
    $form['actions']['submit']['#ajax'] = [
      'callback' => '_renify_tournament_ajax_submit',
      'event' => 'click',
    ];
  }

  if ($form_display && $form_display->getMode() === 'score') {
    // Add our custom AJAX callback to the submit button.
    $form['actions']['submit']['#ajax'] = [
      'callback' => '_renify_tournament_ajax_submit',
      'event' => 'click',
    ];
  }
}

function renify_tournament_node_presave(\Drupal\node\NodeInterface $node) {
  if ($node->bundle() === 'match_tournament') {
    \Drupal::service('renify_tournament.score_generator')->save($node);
  }
}

/**
 * AJAX callback to close modal and redirect to a specific node's alias.
 */
function _renify_tournament_ajax_submit(array $form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $response = new AjaxResponse();

  if ($form_state->hasAnyErrors()) {
    return $form;
  }

  $url = \Drupal::request()->query->get('redirect');

  if ($url) {
    $response->addCommand(new CloseModalDialogCommand());
    $response->addCommand(new RedirectCommand($url));
  }
  else {
    $response->addCommand(new CloseModalDialogCommand());
    $response->addCommand(new RedirectCommand('/'));
  }

  return $response;
}
